FROM python:3.11.4-slim-bookworm

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY scripts scripts
RUN chmod +x scripts/*.sh

COPY src src

ENV PYTHONPATH=/app

CMD ["bash", "scripts/entrypoint-prod.sh"]