FROM python:3.11.4-slim-bookworm

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY scripts scripts
RUN chmod +x scripts/*.sh

ENV PYTHONPATH="/app"

COPY src src

CMD ["bash", "scripts/entrypoint-prod.sh"]
