FROM python:3.11.4-slim-buster

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

RUN chmod +x scripts/entrypoint-jupyter.sh

ENV PYTHONPATH=/app

CMD ["bash", "scripts/entrypoint-jupyter.sh"]