[project]
name = "otus-model-as-a-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.8"
dependencies = [
    "fastapi==0.141.1",
    "loguru==0.7.3",
    "pandas==3.0.5",
    "requests==2.34.2",
    "pytest==9.1.1",
    "scikit-learn==1.9.0",
    "uvicorn==0.52.1",
    "isort==8.0.1",
    "black==26.5.1",
    "ruff==0.16.2"
]
