# deployment.yaml - Otus Model as a Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-maas
  namespace: otus-maas
  labels:
    app: otus-maas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otus-maas
  template:
    metadata:
      labels:
        app: otus-maas
    spec:
      containers:
        - name: fastapi-app
          image: nickosipov/otus-model-as-a-service:0.0.103
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: otus-maas-configmap
